"""Добавлено в таблицу мастер, столбец telegram.id

Revision ID: a3848c6575e2
Revises: fe98800ea76c
Create Date: 2025-11-19 14:48:07.461027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3848c6575e2'
down_revision: Union[str, Sequence[str], None] = 'fe98800ea76c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('masters', sa.Column('telegram_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'masters', ['telegram_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'masters', type_='unique')
    op.drop_column('masters', 'telegram_id')
    # ### end Alembic commands ###
