"""Добавлено поле роли в таблицу мастеров

Revision ID: bd0f87ae06f1
Revises: a3848c6575e2
Create Date: 2025-11-30 13:02:57.922192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd0f87ae06f1'
down_revision: Union[str, Sequence[str], None] = 'a3848c6575e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('masters', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('masters', 'role')
    # ### end Alembic commands ###
