"""add avatar to masters

Revision ID: db874683e3dd
Revises: bd0f87ae06f1
Create Date: 2025-12-31 16:53:42.499540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db874683e3dd'
down_revision: Union[str, Sequence[str], None] = 'bd0f87ae06f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('masters', sa.Column('avatar', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('masters', 'avatar')
    # ### end Alembic commands ###
